name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-20.04
    if: >
      github.event_name == 'push' ||
      github.event.pull_request.head.repo.full_name != github.repository

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: make install

      - name: Build
        run: make build

      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: ${{ env.ARTIFACT_PATH }}

      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.PATCH_VERSION }}
          release_name: v${{ env.PATCH_VERSION }} for MAS ${{ env.MAS_VERSION }}
          draft: true

      - name: Upload Release Asset
        if: startsWith(github.ref, 'refs/tags/')
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          asset_name: ${{ env.ARTIFACT_NAME }}
          asset_path: ${{ env.ARTIFACT_PATH }}
          asset_content_type: application/zip
          upload_url: ${{ steps.create_release.outputs.upload_url }}

  check-translate:
    runs-on: ubuntu-20.04
    if: >
      github.event_name == 'push' ||
      github.event.pull_request.head.repo.full_name != github.repository

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: make install

      - name: Check translates
        run: make check

      - if: failure()
        name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: Check translates error report
          path: ./error_report.tab
