name: Extract Dialogue

on:
  workflow_dispatch:
    inputs:
      base:
        description: Comparison starting point
        required: true
      compare:
        description: Comparison endpoint
        required: true

jobs:
  dialogue:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Extract Dialogue in base version
        run: |
          make dialogue 'MAS_VERSION := ${{ github.event.inputs.base }}'
          mkdir artifact
          mv ./dialogue.tab ./artifact/${{ github.event.inputs.base }}_dialogue.tab

      - name: Extract Dialogue in compare version
        run: |
          make dialogue 'MAS_VERSION := ${{ github.event.inputs.compare }}'
          mv ./dialogue.tab ./artifact/${{ github.event.inputs.compare }}_dialogue.tab

      - name: diff
        continue-on-error: true
        run: |
          diff -u <(cut artifact/${{ github.event.inputs.base }}_dialogue.tab -f 1,2,3,4) --label ${{ github.event.inputs.base }} \
                  <(cut artifact/${{ github.event.inputs.compare }}_dialogue.tab -f 1,2,3,4) --label ${{ github.event.inputs.compare }} > artifact/dialogue.diff

      - name: Upload dialogue.tab
        uses: actions/upload-artifact@v4
        with:
          name: dialogue.tab
          path: artifact
