name: Extract Dialogue

on:
  repository_dispatch:
    types: [extract_dialogue]
  workflow_dispatch:

jobs:
  dialogue:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get newest versions
        run: |
          NEWEST_VERSION=`curl -sL https://api.github.com/repos/Monika-After-Story/MonikaModDev/releases/latest -s | jq .tag_name -r`
          echo "NEWEST_VERSION=$NEWEST_VERSION"
          echo NEWEST_VERSION=$NEWEST_VERSION >> $GITHUB_ENV

      - name: Extract Dialogue in current version
        run: |
          make dialogue
          mkdir artifact
          mv ./dialogue.tab ./artifact/${{ env.CURRENT_VERSION }}_dialogue.tab

      - name: Extract Dialogue in newest version
        run: |
          make dialogue 'MAS_VERSION := ${{ env.NEWEST_VERSION }}'
          mv ./dialogue.tab ./artifact/${{ env.NEWEST_VERSION }}_dialogue.tab

      - name: diff
        continue-on-error: true
        run: |
          diff -u <(cut artifact/${{ env.CURRENT_VERSION }}_dialogue.tab -f 1,2,3,4) --label ${{ env.CURRENT_VERSION }} \
                  <(cut artifact/${{ env.NEWEST_VERSION }}_dialogue.tab -f 1,2,3,4) --label ${{ env.NEWEST_VERSION }} > artifact/dialogue.diff

      - name: Upload dialogue.tab
        uses: actions/upload-artifact@v1
        with:
          name: dialogue.tab
          path: artifact
