name: Update translate files

on:
  push:
    branches:
      - "master"
  repository_dispatch:
    types: [update_translate]
  schedule:
    - cron: "0 21 * * *"
  workflow_dispatch:

jobs:
  translate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout via SSH
        uses: actions/checkout@v2
        with:
          ssh-key: ${{ secrets.ACTIONS_DEPLOY_KEY }}

      - name: Download translate file
        run: |
          curl -s -L ${{ secrets.TRANSLATE_URL }} | base64 -d > scripts.zip
          unzip -oq scripts.zip -d patch/game/tl/Japanese/
          rm scripts.zip

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          branch: translate
          commit-message: ":sparkles: 翻訳の更新"
          author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          title: 翻訳の更新
          body: |
            この Pull Request は GitHub Actions により自動生成されています。
            毎朝 6 時に翻訳所から最新の翻訳が反映されます。
          labels: automated pr
          assignees: proudust
          reviewers: proudust
